# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - waist_group_controller
    - right_arm_group_controller
    - left_arm_group_controller
    - right_hand_group_controller
    - left_hand_group_controller

  waist_group_controller:
    type: FollowJointTrajectory
    joints:
      - waist_yaw_joint
      - waist_roll_joint
      - waist_pitch_joint
    action_ns: follow_joint_trajectory
    default: true
  right_arm_group_controller:
    type: FollowJointTrajectory
    joints:
      - right_shoulder_pitch_joint
      - right_shoulder_roll_joint
      - right_shoulder_yaw_joint
      - right_elbow_joint
      - right_wrist_roll_joint
      - right_wrist_pitch_joint
      - right_wrist_yaw_joint
    action_ns: follow_joint_trajectory
    default: true
  left_arm_group_controller:
    type: FollowJointTrajectory
    joints:
      - left_shoulder_pitch_joint
      - left_shoulder_roll_joint
      - left_shoulder_yaw_joint
      - left_elbow_joint
      - left_wrist_roll_joint
      - left_wrist_pitch_joint
      - left_wrist_yaw_joint
    action_ns: follow_joint_trajectory
    default: true
  right_hand_group_controller:
    type: GripperCommand
    joints:
      - right_hand_index_0_joint
      - right_hand_index_1_joint
      - right_hand_middle_0_joint
      - right_hand_middle_1_joint
      - right_hand_thumb_0_joint
      - right_hand_thumb_1_joint
      - right_hand_thumb_2_joint
    action_ns: gripper_cmd
    default: true
  left_hand_group_controller:
    type: GripperCommand
    joints:
      - left_hand_index_0_joint
      - left_hand_index_1_joint
      - left_hand_middle_0_joint
      - left_hand_middle_1_joint
      - left_hand_thumb_0_joint
      - left_hand_thumb_1_joint
      - left_hand_thumb_2_joint
    action_ns: gripper_cmd
    default: true