# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    waist_group_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    right_arm_group_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    left_arm_group_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    right_hand_group_controller:
      type: position_controllers/GripperActionController


    left_hand_group_controller:
      type: position_controllers/GripperActionController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

waist_group_controller:
  ros__parameters:
    joints:
      - waist_yaw_joint
      - waist_roll_joint
      - waist_pitch_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
right_arm_group_controller:
  ros__parameters:
    joints:
      - right_shoulder_pitch_joint
      - right_shoulder_roll_joint
      - right_shoulder_yaw_joint
      - right_elbow_joint
      - right_wrist_roll_joint
      - right_wrist_pitch_joint
      - right_wrist_yaw_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
left_arm_group_controller:
  ros__parameters:
    joints:
      - left_shoulder_pitch_joint
      - left_shoulder_roll_joint
      - left_shoulder_yaw_joint
      - left_elbow_joint
      - left_wrist_roll_joint
      - left_wrist_pitch_joint
      - left_wrist_yaw_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
right_hand_group_controller:
  ros__parameters:
    joint: right_hand_index_0_joint
left_hand_group_controller:
  ros__parameters:
    joint: left_hand_index_0_joint